apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "prova-argocd2"
spec:
  destination:
    namespace: rhdh
    server: https://kubernetes.default.svc
  project: default
  source:
    path: manifests/base
    repoURL: https://github.com/BlackMamba97s/prova-argocd2
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
